-- CreateTable
CREATE TABLE "Call911Event" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "call911Id" TEXT NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "Call911Event_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Call911Event" ADD CONSTRAINT "Call911Event_call911Id_fkey" FOREIGN KEY ("call911Id") REFERENCES "Call911"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
