name: Bug Report
description: Create a report to help improve SnailyCAD
labels: "bug"
body:
  - type: input
    attributes:
      label: What version of Node.js are you using?
      description: "For example: 14.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: What version of npm are you using?
      description: "For example: 7.10.0"
    validations:
      required: false
  - type: input
    attributes:
      label: What operating system are you using?
      description: "For example: Ubuntu, Windows, etc"
    validations:
      required: true
  - type: input
    attributes:
      label: What version of SnailyCAD are you currently using?
      description: "For example: 1.0.0-beta.88"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.
    validations:
      required: false
