contact_links:
  - name: General Support (SnailyCAD Community)
    url: https://discord.gg/eGnrPqEH7U
    about: Questions about installation process and general questions should be sent via Discord if possible
