/*
  Warnings:

  - The values [USER_DEFINED_CALLSIGNS_COMBINED_UNIT] on the enum `Feature` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "Feature_new" AS ENUM ('BLEETER', 'TOW', 'TAXI', 'COURTHOUSE', 'TRUCK_LOGS', 'AOP', 'BUSINESS', 'ALLOW_DUPLICATE_CITIZEN_NAMES', 'DISCORD_AUTH', 'CALLS_911', 'WEAPON_REGISTRATION', 'SOCIAL_SECURITY_NUMBERS', 'CUSTOM_TEXTFIELD_VALUES', 'DISALLOW_TEXTFIELD_SELECTION', 'ACTIVE_DISPATCHERS', 'ACTIVE_INCIDENTS', 'ALLOW_CITIZEN_UPDATE_LICENSE', 'ALLOW_REGULAR_LOGIN', 'RADIO_CHANNEL_MANAGEMENT', 'ALLOW_CITIZEN_DELETION_BY_NON_ADMIN', 'DL_EXAMS', 'DMV', 'BADGE_NUMBERS', 'USER_API_TOKENS', 'CITIZEN_RECORD_APPROVAL', 'COMMON_CITIZEN_CARDS', 'STEAM_OAUTH', 'CREATE_USER_CITIZEN_LEO', 'LEO_TICKETS', 'LEO_BAIL', 'COURTHOUSE_POSTS', 'WEAPON_EXAMS', 'ACTIVE_WARRANTS', 'CITIZEN_DELETE_ON_DEAD', 'PANIC_BUTTON', 'WARRANT_STATUS_APPROVAL', 'DIVISIONS', 'TONES', 'LICENSE_EXAMS', 'CITIZEN_CREATION_RECORDS', 'BUREAU_OF_FIREARMS', 'CALL_911_APPROVAL', 'FORCE_DISCORD_AUTH', 'FORCE_STEAM_AUTH', 'EDITABLE_SSN', 'EDITABLE_VIN', 'SIGNAL_100_CITIZEN', 'FORCE_ACCOUNT_PASSWORD', 'USER_DEFINED_CALLSIGN_COMBINED_UNIT');
ALTER TABLE "cad" ALTER COLUMN "disabledFeatures" TYPE "Feature_new"[] USING ("disabledFeatures"::text::"Feature_new"[]);
ALTER TABLE "CadFeature" ALTER COLUMN "feature" TYPE "Feature_new" USING ("feature"::text::"Feature_new");
ALTER TYPE "Feature" RENAME TO "Feature_old";
ALTER TYPE "Feature_new" RENAME TO "Feature";
DROP TYPE "Feature_old";
COMMIT;
